"""
Synthetic Toeplitz-MRF time-series generator  (TICC paper, Section 6).

Each cluster is a zero-mean Gaussian whose (n*w) x (n*w) inverse covariance Theta
is block-Toeplitz, built from random sparse blocks A(0)..A(w-1). A time series is
then produced from a sequence of cluster segments by drawing each new n-vector from
its conditional Gaussian given the previous w-1 observations (so, at a switch, the
new sample still depends on data generated by the previous cluster -- as in the
paper).
"""

import numpy as np


def random_toeplitz_theta(n, w, rng, edge_prob=0.2, w_lo=0.5, w_hi=0.9):
    """
    Build one cluster's ground-truth block-Toeplitz inverse covariance Theta.

    A(0) is a symmetric sparse block; A(1..w-1) are directed sparse blocks, each an
    Erdos-Renyi graph with `edge_prob` edge probability. Edge weights have random
    sign and magnitude in [w_lo, w_hi] -- a zero-mean (symmetric) distribution, as in
    the paper, but bounded away from 0 so edges are statistically recoverable (the
    standard convention in GMRF structure-recovery benchmarks; pure N(0,1) weights
    put many edges below the noise floor and cap recovery near 0.6). G is assembled
    block-Toeplitz and shifted by (0.1 + |min-eig|) I to be positive definite.
    """
    blocks = []
    for m in range(w):
        mask = rng.random((n, n)) < edge_prob
        weights = rng.choice([-1.0, 1.0], (n, n)) * rng.uniform(w_lo, w_hi, (n, n))
        A = mask * weights
        if m == 0:                                   # A(0) must be symmetric
            A = np.triu(A)
            A = A + A.T - np.diag(np.diag(A))
        blocks.append(A)

    N = n * w
    G = np.zeros((N, N))
    for a in range(w):
        for b in range(w):
            m = b - a
            block = blocks[m] if m >= 0 else blocks[-m].T
            G[a * n:(a + 1) * n, b * n:(b + 1) * n] = block
    G = 0.5 * (G + G.T)                              # enforce exact symmetry

    c = np.linalg.eigvalsh(G).min()
    Theta = G + (0.1 + abs(c)) * np.eye(N)
    return Theta


def _conditional_params(Theta, n, w):
    """Conditional of the last n-block given the earlier n(w-1) blocks, from Theta."""
    Th_xx = Theta[-n:, -n:]
    Th_xh = Theta[-n:, :n * (w - 1)]
    cov_x = np.linalg.inv(Th_xx)
    A_cond = -cov_x @ Th_xh                          # conditional mean map: x_mean = A_cond @ h
    L_x = np.linalg.cholesky(cov_x)                  # conditional covariance factor
    return A_cond, L_x


def generate_series(sequence, seg_len, n=5, w=5, edge_prob=0.2, seed=0, thetas=None):
    """
    Generate a multivariate time series from a sequence of cluster segments.

    Parameters
    ----------
    sequence : list of cluster ids, e.g. [1, 2, 1] (1-indexed, as in the paper).
    seg_len : number of observations per segment.
    n, w : dimension and window size (paper uses n=5, w=5).
    thetas : optional dict {cluster_id: Theta} to reuse ground-truth models across
             calls (e.g. the sample-size sweep). If None, fresh ones are drawn.

    Returns
    -------
    X : (T, n) time series, T = len(sequence) * seg_len.
    labels : (T,) ground-truth cluster id per time step (same ids as `sequence`).
    thetas : dict {cluster_id: Theta} of the ground-truth models used.
    """
    rng = np.random.default_rng(seed)
    ids = sorted(set(sequence))
    if thetas is None:
        thetas = {c: random_toeplitz_theta(n, w, rng, edge_prob) for c in ids}
    cond = {c: _conditional_params(thetas[c], n, w) for c in ids}

    labels = np.repeat(sequence, seg_len)
    T = labels.size
    X = np.zeros((T, n))

    # first window: draw the whole length-w window from the first cluster's covariance
    c0 = sequence[0]
    L0 = np.linalg.cholesky(np.linalg.inv(thetas[c0]))
    X[:w] = (L0 @ rng.standard_normal(n * w)).reshape(w, n)

    # roll forward one observation at a time via the conditional Gaussian
    for t in range(w, T):
        A_cond, L_x = cond[labels[t]]
        h = X[t - (w - 1):t].reshape(-1)             # previous w-1 observations
        X[t] = A_cond @ h + L_x @ rng.standard_normal(n)

    return X, labels, thetas
